packages:
  - data
  - website
  - noviq_client

allowBuilds:
  esbuild: set this to true or false

onlyBuiltDependencies:
  - '@reown/appkit'
  - bufferutil
  - esbuild
  - keccak
  - utf-8-validate
